FROM golang:1.16 as build

RUN apt-get update && apt-get install -y ninja-build

WORKDIR /go/src
RUN git clone https://github.com/teramont/go2-lab-1
WORKDIR /go/src/go2-lab-1
RUN go get -u ./build/cmd/bood

WORKDIR /go/src/go2-lab-2
COPY . .

WORKDIR /go/src/go2-lab-2/integration

ENTRYPOINT bood 2>&1 | tee integration.log